# Generated by Django 4.2.1 on 2023-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma_fight_predictor_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fighter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=40)),
                ("last_name", models.CharField(blank=True, max_length=40)),
                ("gender", models.CharField(max_length=6)),
                ("style", models.CharField(blank=True, max_length=30)),
                ("record", models.CharField(blank=True, max_length=30)),
                ("height", models.CharField(blank=True, max_length=10)),
                ("stance", models.CharField(blank=True, max_length=10)),
                ("dob", models.CharField(blank=True, max_length=10)),
                ("weight", models.CharField(blank=True, max_length=10)),
                ("reach", models.CharField(blank=True, max_length=10)),
                ("slpm", models.FloatField(default=0.0)),
                ("str_acc", models.CharField(blank=True, max_length=5)),
                ("sapm", models.FloatField(default=0.0)),
                ("str_def", models.CharField(blank=True, max_length=5)),
                ("td_avg", models.FloatField(default=0.0)),
                ("td_acc", models.CharField(blank=True, max_length=5)),
                ("td_def", models.CharField(blank=True, max_length=5)),
                ("sub_avg", models.FloatField(default=0.0)),
            ],
        ),
    ]
