# Generated by Django 4.2.1 on 2023-10-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma_fight_predictor_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighter",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="fighter",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
