# Generated by Django 4.2.1 on 2026-06-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "mma_fight_predictor_api",
            "0002_alter_fighter_first_name_alter_fighter_last_name",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fighter_a_name", models.CharField(max_length=120)),
                ("fighter_b_name", models.CharField(max_length=120)),
                ("prob_a", models.FloatField()),
                ("favorite", models.CharField(max_length=120)),
                ("model_name", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "model_trained_at",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "actual_winner",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("correct", models.BooleanField(blank=True, null=True)),
                ("scored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_predictions",
                        to="mma_fight_predictor_api.fight",
                    ),
                ),
                (
                    "fighter_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="model_prediction_fighter_a",
                        to="mma_fight_predictor_api.fighter",
                    ),
                ),
                (
                    "fighter_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="model_prediction_fighter_b",
                        to="mma_fight_predictor_api.fighter",
                    ),
                ),
            ],
        ),
    ]
