# Generated by Django 4.2.1 on 2023-05-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma_fight_predictor_api", "0002_fighter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighter",
            name="gender",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
