# Generated by Django 4.2.1 on 2023-05-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mma_fight_predictor_api",
            "0004_alter_fighter_dob_alter_fighter_height_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighter",
            name="style",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
