# Generated by Django 4.2.1 on 2023-05-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma_fight_predictor_api", "0005_alter_fighter_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighter",
            name="last_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
