# Generated by Django 4.2.1 on 2023-05-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma_fight_predictor_api", "0007_fight"),
    ]

    operations = [
        migrations.AddField(
            model_name="fight",
            name="format",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
