# Generated by Django 4.2.1 on 2023-07-27 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mma_fight_predictor_api", "0016_alter_prediction_defense_winner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fight",
            name="blue_fighter",
        ),
        migrations.RemoveField(
            model_name="fight",
            name="red_fighter",
        ),
        migrations.AddField(
            model_name="fight",
            name="blue_fighter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blue_fighter",
                to="mma_fight_predictor_api.fighter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fight",
            name="red_fighter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="red_fighter",
                to="mma_fight_predictor_api.fighter",
            ),
            preserve_default=False,
        ),
    ]
