# Generated by Django 4.2.1 on 2023-07-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mma_fight_predictor_api",
            "0017_remove_fight_blue_fighter_remove_fight_red_fighter_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fight",
            name="weight",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
