# Generated by Django 4.2.1 on 2023-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma_fight_predictor_api", "0019_remove_fight_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fight",
            name="fight_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
