# Generated by Django 4.2.1 on 2023-08-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mma_fight_predictor_api",
            "0021_alter_fight_b_body_alter_fight_b_clinch_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fight",
            name="fight_type",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="fight",
            name="location",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="fight",
            name="loser",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="fight",
            name="winner",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
