# Generated by Django 4.2.1 on 2023-08-21 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "mma_fight_predictor_api",
            "0022_alter_fight_fight_type_alter_fight_location_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_data", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fighter",
                        to="mma_fight_predictor_api.fighter",
                    ),
                ),
            ],
        ),
    ]
