# Generated by Django 4.2.1 on 2023-09-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma_fight_predictor_api", "0027_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="access_token",
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name="token",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
