# Generated by Django 4.2.1 on 2023-10-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mma_fight_predictor_api",
            "0029_prediction_blue_fighter_betting_odds_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
