# Generated by Django 4.2.1 on 2023-10-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma_fight_predictor_api", "0030_usergroups"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
