WEIGHT_CLASSES = {
    "Women's Strawweight Bout": 0,
    "Women's Flyweight Bout": 1,
    "Women's Bantamweight Bout": 2,
    "Women's Featherweight Bout": 3,
    "Flyweight Bout": 4,
    "UFC Flyweight Title Bout": 4,
    "Bantamweight Bout": 5,
    "UFC Bantamweight Title Bout": 5,
    "Featherweight Bout": 6,
    "UFC Featherweight Title Bout": 6,
    "Lightweight Bout": 7,
    "UFC Lightweight Title Bout": 7,
    "Welterweight Bout": 8,
    "UFC Welterweight Title Bout": 8,
    "Middleweight Bout": 9,
    "UFC Middleweight Title Bout": 9,
    "Light Heavyweight Bout": 10,
    "UFC Light Heavyweight Title Bout": 10,
    "Heavyweight Bout": 11,
    "UFC Heavyweight Title Bout": 11,
    "Super Heavyweight Bout": 12
}
